server:
  port: 5002

intent-config:
  allowed-intents:
    - CreateShipment
    - TrackShipment
    - ReturnShipment
    - RescheduleDelivery
    - ReportIssue
    - ConfirmIntent
    - CancelIntent
  confidence-threshold: 80      # Minimum confidence to accept an intent (0–100)
  temperature: 0.2              # Lower = more predictable, higher = more creative
  max-tokens: 50                # How many tokens to generate in LLM response

azure:
  openai:
    endpoint: https://ups-jarvis-ai-foundry.cognitiveservices.azure.com/      # Replace with your Azure OpenAI endpoint
    api-key: CToGIgq9UUuTKNwCaT93P7J4FF3pmzP2PRJasy6FEWGRIQGYGOS2JQQJ99BGACYeBjFXJ3w3AAAAACOGI2co
    deployment: gpt-4
    api-version: 2025-01-01-preview
