server:
  port: 5002

intent-config:
  allowed-intents:
    - CreateShipment
    - TrackShipment
    - ReturnShipment
    - RescheduleDelivery
    - ReportIssue
    - ConfirmIntent
    - CancelIntent
  confidence-threshold: 80      # Minimum confidence to accept an intent (0–100)
  temperature: 0.2              # Lower = more predictable, higher = more creative
  max-tokens: 50                # How many tokens to generate in LLM response

azure:
  openai:
    endpoint: https://<your-openai-endpoint>.openai.azure.com      # Replace with your Azure OpenAI endpoint
    api-key: sk-xxxxxxxxxxxxxxxxxxxx                             # Set as environment variable in production!
    deployment: logistics-intents                                  # Your deployment name in Azure OpenAI
    api-version: 2024-05-01                                        # Set to your API version, update if needed